server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pfe
    username: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create

  logging:
    level:
      org.springframework.web: DEBUG
      ma.pfe: DEBUG

